export enum GameStatus {
    WAITING = 'WAITING',
    STARTING = 'STARTING',
    LOCKING = 'LOCKING',
    IN_PROGRESS = 'IN_PROGRESS',
    PAYOUT = 'PAYOUT',
    REFUNDING = 'REFUNDING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}

export enum TransactionType {
    DEPOSIT = 'DEPOSIT',
    WITHDRAWAL = 'WITHDRAWAL',
    GAME_ENTRY = 'GAME_ENTRY',
    PRIZE_WIN = 'PRIZE_WIN',
    REFUND = 'REFUND',
    FIRST_DEPOSIT_BONUS = 'FIRST_DEPOSIT_BONUS',
    CASHBACK_BONUS = 'CASHBACK_BONUS',
    ADMIN_REAL_ADJUSTMENT = 'ADMIN_REAL_ADJUSTMENT',
    ADMIN_BONUS_ADJUSTMENT = 'ADMIN_BONUS_ADJUSTMENT',
}

export enum PaymentStatus {
    PENDING = 'PENDING',
    PENDING_REVIEW = 'PENDING_REVIEW',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
}

export enum UserRole {
    PLAYER = 'PLAYER',
    ADMIN = 'ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum PatternType {
    ANY_LINE = 'ANY_LINE',
    DIAGONAL = 'DIAGONAL',
    FULL_CARD = 'FULL_CARD',
    X_PATTERN = 'X_PATTERN',
    CORNERS = 'CORNERS',
}

export enum NotificationType {
    GAME_CANCELLED = 'GAME_CANCELLED',
    REFUND_PROCESSED = 'REFUND_PROCESSED',
    DEPOSIT_APPROVED = 'DEPOSIT_APPROVED',
    DEPOSIT_REJECTED = 'DEPOSIT_REJECTED',
    WITHDRAWAL_PROCESSED = 'WITHDRAWAL_PROCESSED',
    GAME_WON = 'GAME_WON',
    GAME_STARTING = 'GAME_STARTING',
    REFERRAL_BONUS = 'REFERRAL_BONUS',
    TOURNAMENT_STARTING = 'TOURNAMENT_STARTING',
    TOURNAMENT_WON = 'TOURNAMENT_WON',
    TOURNAMENT_ELIMINATED = 'TOURNAMENT_ELIMINATED',
    CASHBACK_AWARDED = 'CASHBACK_AWARDED',
}

export enum TournamentStatus {
    REGISTRATION = 'REGISTRATION',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}
